//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public int Id { get; set; }
        public string CarNum { get; set; }
        public string Region { get; set; }
        public string LicenceNum { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Photo { get; set; }
        public string Status { get; set; }
    }
}
