//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenceHistory
    {
        public int Id { get; set; }
        public System.DateTime LicenceDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public string Categories { get; set; }
        public string LicenceSeries { get; set; }
        public string LicenceNumber { get; set; }
        public string Status { get; set; }
        public Nullable<int> LicenceId { get; set; }
        public System.DateTime DateChanged { get; set; }
        public string Comment { get; set; }
    
        public virtual Licence Licence { get; set; }
    }
}
