//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomColor> CustomColor { get; set; }
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<EngineType> EngineType { get; set; }
        public virtual DbSet<Fine> Fine { get; set; }
        public virtual DbSet<Licence> Licence { get; set; }
        public virtual DbSet<LicenceCategory> LicenceCategory { get; set; }
        public virtual DbSet<LicenceHistory> LicenceHistory { get; set; }
        public virtual DbSet<RegionCode> RegionCode { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Vehicle> Vehicle { get; set; }
        public virtual DbSet<VehicleHistory> VehicleHistory { get; set; }
        public virtual DbSet<VehicleImage> VehicleImage { get; set; }
    }
}
