//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionCode
    {
        public string Name { get; set; }
        public Nullable<int> SubjectCode { get; set; }
        public string Code { get; set; }
        public string OkatoCode { get; set; }
        public string Iso { get; set; }
    }
}
