//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleImage
    {
        public int Id { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> VehicleId { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
